<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>57caaaab-fb57-458b-b8f3-59a23585bf23</elementGuidId>
    <imagePath></imagePath>
    <name>button_send</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/form[1]/div[4]/a[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="my-2\\ px-4\\ mx-auto\\ btn\\ btn-dark"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Send')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=button[name=\\"Send\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Send</value>
        <webElementGuid>d46234d3-b759-4e2a-9616-59bd1d1de296</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>d46234d3-b759-4e2a-9616-59bd1d1de296</webElementGuid>
    </webElementProperties>
</WebElementEntity>