<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5789ea2a-9a1b-435b-8754-78f4018fa7e9</elementGuidId>
    <imagePath></imagePath>
    <name>button_send</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/form[1]/div[4]/a[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="my-2\\ px-4\\ mx-auto\\ btn\\ btn-dark"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Send')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=button[name="Send"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Send</value>
        <webElementGuid>993527f4-e5fb-4e06-a6b8-e39be5da684d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>993527f4-e5fb-4e06-a6b8-e39be5da684d</webElementGuid>
    </webElementProperties>
</WebElementEntity>