<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fac82895-0193-4047-b1b6-a5162590ccd6</elementGuidId>
    <imagePath></imagePath>
    <name>button_add_to_cart</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/div[2]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\31  [class="btn\\ btn-dark\\ m-1"]:nth-child(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Add to Cart')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id="\\31 "] &gt;&gt; internal:role=button[name="Add to Cart"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add to Cart</value>
        <webElementGuid>993527f4-e5fb-4e06-a6b8-e39be5da684d</webElementGuid>
    </webElementProperties>
</WebElementEntity>