<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3a176a0b-9107-45ee-9506-06c4041023a7</elementGuidId>
    <imagePath></imagePath>
    <name>button_shop_now</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/a[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="shopBtn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Shop Now')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Shop Now</value>
        <webElementGuid>80a8faa5-b4db-46f3-b7d5-41cabf58706a</webElementGuid>
    </webElementProperties>
</WebElementEntity>