<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>036a7e97-018c-407b-88ba-4406b087bd5d</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_buy_now</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[2]/div[6]/div[1]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#\\35  [class="btn\\ btn-dark\\ m-1"]:nth-child(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Buy Now')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id="\\35 "] &gt;&gt; internal:role=link[name="Buy Now"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Buy Now</value>
        <webElementGuid>993527f4-e5fb-4e06-a6b8-e39be5da684d</webElementGuid>
    </webElementProperties>
</WebElementEntity>