<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4030125e-8fed-4b6e-81ce-f916d1e2a476</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_continue_to_checkout</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/form[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="w-100\\ btn\\ btn-primary\\ "]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Continue to checkout')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Continue to checkout"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Continue to checkout</value>
        <webElementGuid>993527f4-e5fb-4e06-a6b8-e39be5da684d</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>993527f4-e5fb-4e06-a6b8-e39be5da684d</webElementGuid>
    </webElementProperties>
</WebElementEntity>