<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fbf47050-c80e-47a5-a580-9fb590c652eb</elementGuidId>
    <imagePath></imagePath>
    <name>button_register</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/form[1]/div[5]/a[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="my-2\\ mx-auto\\ btn\\ btn-dark"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'Register')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>["internal:role=button[name=\\"Register\\"i]"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Register</value>
        <webElementGuid>d46234d3-b759-4e2a-9616-59bd1d1de296</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>d46234d3-b759-4e2a-9616-59bd1d1de296</webElementGuid>
    </webElementProperties>
</WebElementEntity>